/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.doggenetics;

/**
 *
 * @author Kenny
 */

import java.util.Scanner;
import java.util.Random;
public class DogGenetics {
    public static void main(String[] args) {
        
        
   /*/= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =\
  /= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =\
 ||                                                               ||
 ||                                                               ||
 ||              DOG GENETICS                                     ||
 ||                        Kenneth Melendez                       ||
 ||                                                               ||
  \= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =/
   \= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =/*/
        

/*===================================================================
        Calling the Scanners
===================================================================*/

        Scanner input = new Scanner(System.in);
        Random randomizer = new Random();
        
/*===================================================================
        Program Text
===================================================================*/        
        
        System.out.println("What is your dogs name?");
        String dogBreedInput = input.nextLine();
        System.out.println("Well then, I have this highly reliable report on " + dogBreedInput + " prestigious background right here.");
        
        int total = 100;
        
        
        //5Breeds output
        /*
        I created a randomizer that randomizes 100 then for each breed it subtracts
        the number generated by the other numbers by the total 100.
        */
        
        int Beagle =  randomizer.nextInt(total);
        int Poodle =  randomizer.nextInt(total - Beagle);
        int GermanSheperd =  randomizer.nextInt(total - Poodle - Beagle);
        int Bulldog =  randomizer.nextInt(total - GermanSheperd - Poodle - Beagle);
        int LabradorRetriever = randomizer.nextInt(total - GermanSheperd - Poodle - Beagle);
        
        //Outcome will always equal 100 because its subtracting the numbers by itself from the total and surrounding numbers.
        
        
/*===================================================================
        Results
===================================================================*/             
        
        System.out.println(" Your dog " + dogBreedInput +  " is");
        System.out.println("% " + Beagle + " Beagle");
        System.out.println("% " + Poodle + " Poodle");
        System.out.println("% " + GermanSheperd + " German Sheperd");
        System.out.println("% " + Bulldog + " Bulldog");
        System.out.println("% " + LabradorRetriever + " Retriever");
        
        

/*=======================================================
                   ____,'`-, 
      _,--'   ,/::.; 
   ,-'       ,/::,' `---.___        ___,_ 
   |       ,:';:/        ;'"`;"`--./ ,-^.;--. 
   |:     ,:';,'         '         `.   ;`   `-. 
    \:.,:::/;/ -:.                   `  | `     `-. 
     \:::,'//__.;  ,;  ,  ,  :.`-.   :. |  ;       :. 
      \,',';/O)^. :'  ;  :   '__` `  :::`.       .:' ) 
      |,'  |\__,: ;      ;  '/O)`.   :::`;       ' ,' 
           |`--''            \__,' , ::::(       ,' 
           `    ,            `--' ,: :::,'\   ,-' 
            | ,;         ,    ,::'  ,:::   |,' 
            |,:        .(          ,:::|   ` 
            ::'_   _   ::         ,::/:| 
           ,',' `-' \   `.      ,:::/,:| 
          | : _  _   |   '     ,::,' ::: 
          | \ O`'O  ,',   ,    :,'   ;:: 
           \ `-'`--',:' ,' , ,,'      :: 
            ``:.:.__   ',-','        ::' 
    -hrr-      `--.__, ,::.         ::' 
                   |:  ::::.       ::' 
                   |:  ::::::    ,::' */        
//=======================================================
        
        
        
        
        
        
        
    }
}
